### PR TITLE
Use ipinfo.io since freegeoip is dead.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Requests to http://freegeoip.net/json/ aren't working anymore. Wanting to change this lib to an active service at ipinfo.io.

### CODE REVIEW

**Comment by UmanShahzad** [comment]
cc @luvaas

**Comment by UmanShahzad** [comment]
Hey Darren, can you check this one out? :) @luvaas

**Comment by luvaas** [comment]
Done!  Thanks for the help, @UmanShahzad

**Comment by UmanShahzad** [comment]
@luvaas thanks to you!

**Pull request merged**
